#pragma once
typedef enum AircraftTypeTD : char {
	AIRCRAFTTD_TRANSPORT,
	AIRCRAFTTD_A10,
	AIRCRAFTTD_HELICOPTER,
	AIRCRAFTTD_CARGO,
	AIRCRAFTTD_ORCA,
	AIRCRAFTTD_COUNT,
	AIRCRAFTTD_NONE = -1,
	AIRCRAFTTD_FIRST = 0
} AircraftTypeTD; 
typedef enum AircraftTypeRA : char {
	AIRCRAFTRA_TRANSPORT,
	AIRCRAFTRA_BADGER,
	AIRCRAFTRA_U2,
	AIRCRAFTRA_MIG,
	AIRCRAFTRA_YAK,
	AIRCRAFTRA_LONGBOW,
	AIRCRAFTRA_HIND,
	AIRCRAFTRA_COUNT,
	AIRCRAFTRA_NONE = -1,
	AIRCRAFTRA_FIRST = 0
} AircraftTypeRA;
