#include "global.h"
#include "housetype.h"
std::map<std::string, HouseType*> HouseType::HouseMapTD;
std::map<std::string, HouseType*> HouseType::HouseMapRA;
static const char* colors[] = { "BAD_STRUCTURE", "BAD_STRUCTURE" };
static const char* names[] = { "harv", "BAD_STRUCTURE" };
static HouseType TDGOOD(HOUSETD_GOOD, "GoodGuy", "GOOD", "GOOD", 0, nullptr, nullptr, false);
static HouseType TDBAD(HOUSETD_BAD, "BadGuy", "BAD_UNIT", "BAD_STRUCTURE", 2, colors, names, false);
static HouseType TDNEUTRAL(HOUSETD_NEUTRAL, "Neutral", "", "", 0, nullptr, nullptr, false);
static HouseType TDSPECIAL(HOUSETD_JP, "Special", "", "", 0, nullptr, nullptr, false);
static HouseType TDMULTI1(HOUSETD_MULTI1, "Multi1", "MULTI1", "MULTI1", 0, nullptr, nullptr, false);
static HouseType TDMULTI2(HOUSETD_MULTI2, "Multi2", "MULTI2", "MULTI2", 0, nullptr, nullptr, false);
static HouseType TDMULTI3(HOUSETD_MULTI3, "Multi3", "MULTI3", "MULTI3", 0, nullptr, nullptr, false);
static HouseType TDMULTI4(HOUSETD_MULTI4, "Multi4", "MULTI4", "MULTI4", 0, nullptr, nullptr, false);
static HouseType TDMULTI5(HOUSETD_MULTI5, "Multi5", "MULTI5", "MULTI5", 0, nullptr, nullptr, false);
static HouseType TDMULTI6(HOUSETD_MULTI6, "Multi6", "MULTI6", "MULTI6", 0, nullptr, nullptr, false);
static HouseType RASPAIN(HOUSERA_SPAIN, "Spain", "SPAIN", "SPAIN", 0, nullptr, nullptr, true);
static HouseType RAGREECE(HOUSERA_GREECE, "Greece", "GREECE", "GREECE", 0, nullptr, nullptr, true);
static HouseType RAUSSR(HOUSERA_USSR, "USSR", "USSR", "USSR", 0, nullptr, nullptr, true);
static HouseType RAENGLAND(HOUSERA_ENGLAND, "England", "ENGLAND", "ENGLAND", 0, nullptr, nullptr, true);
static HouseType RAUKRAINE(HOUSERA_UKRAINE, "Ukraine", "UKRAINE", "UKRAINE", 0, nullptr, nullptr, true);
static HouseType RAGERMANY(HOUSERA_GERMANY, "Germany", "GERMANY", "GERMANY", 0, nullptr, nullptr, true);
static HouseType RAFRANCE(HOUSERA_FRANCE, "France", "FRANCE", "FRANCE", 0, nullptr, nullptr, true);
static HouseType RATURKEY(HOUSERA_TURKEY, "Turkey", "TURKEY", "TURKEY", 0, nullptr, nullptr, true);
static HouseType RAGOOD(HOUSERA_GOOD, "GoodGuy", "GOOD", "GOOD", 0, nullptr, nullptr, true);
static HouseType RABAD(HOUSERA_BAD, "BadGuy", "BAD", "BAD", 0, nullptr, nullptr, true);
static HouseType RANEUTRAL(HOUSERA_NEUTRAL, "Neutral", "", "", 0, nullptr, nullptr, true);
static HouseType RASPECIAL(HOUSERA_JP, "Special", "", "", 0, nullptr, nullptr, true);
static HouseType RAMULTI1(HOUSERA_MULTI1, "Multi1", "MULTI1", "MULTI1", 0, nullptr, nullptr, true);
static HouseType RAMULTI2(HOUSERA_MULTI2, "Multi2", "MULTI2", "MULTI2", 0, nullptr, nullptr, true);
static HouseType RAMULTI3(HOUSERA_MULTI3, "Multi3", "MULTI3", "MULTI3", 0, nullptr, nullptr, true);
static HouseType RAMULTI4(HOUSERA_MULTI4, "Multi4", "MULTI4", "MULTI4", 0, nullptr, nullptr, true);
static HouseType RAMULTI5(HOUSERA_MULTI5, "Multi5", "MULTI5", "MULTI5", 0, nullptr, nullptr, true);
static HouseType RAMULTI6(HOUSERA_MULTI6, "Multi6", "MULTI6", "MULTI6", 0, nullptr, nullptr, true);
static HouseType RAMULTI7(HOUSERA_MULTI7, "Multi7", "MULTI7", "MULTI7", 0, nullptr, nullptr, true);
static HouseType RAMULTI8(HOUSERA_MULTI8, "Multi8", "MULTI8", "MULTI8", 0, nullptr, nullptr, true);
