#include "global.h"
#include "overlaytype.h"
#include "tileset.h"
std::map<std::string, OverlayType*> OverlayType::OverlayMapTD;
std::map<std::string, OverlayType*> OverlayType::OverlayMapRA;
std::vector<OverlayType*> OverlayType::Tiberium;
std::vector<OverlayType*> OverlayType::Gold;
std::vector<OverlayType*> OverlayType::Gems;
static OverlayType TDSANDBAG(OVERLAYTD_SANDBAG_WALL, "sbag", "TEXT_STRUCTURE_TITLE_GDI_SANDBAGS", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_WALL, false);
static OverlayType TDCYCLONE(OVERLAYTD_CYCLONE_WALL, "cycl", "TEXT_STRUCTURE_TITLE_GDI_CHAIN_LINK", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_WALL, false);
static OverlayType TDBRICK(OVERLAYTD_BRICK_WALL, "brik", "TEXT_STRUCTURE_TITLE_GDI_CONCRETE", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_WALL, false);
static OverlayType TDBARBWIRE(OVERLAYTD_BARBWIRE_WALL, "barb", "TEXT_STRUCTURE_RA_BARB", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_WALL, false);
static OverlayType TDWOOD(OVERLAYTD_WOOD_WALL, "wood", "TEXT_STRUCTURE_TD_WOOD", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_WALL, false);
static OverlayType TDTIBERIUM1(OVERLAYTD_TIBERIUM1, "ti1", "ti1", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM2(OVERLAYTD_TIBERIUM2, "ti2", "ti2", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM3(OVERLAYTD_TIBERIUM3, "ti3", "ti3", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM4(OVERLAYTD_TIBERIUM4, "ti4", "ti4", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM5(OVERLAYTD_TIBERIUM5, "ti5", "ti5", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM6(OVERLAYTD_TIBERIUM6, "ti6", "ti6", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM7(OVERLAYTD_TIBERIUM7, "ti7", "ti7", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM8(OVERLAYTD_TIBERIUM8, "ti8", "ti8", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM9(OVERLAYTD_TIBERIUM9, "ti9", "ti9", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM10(OVERLAYTD_TIBERIUM10, "ti10", "ti10", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM11(OVERLAYTD_TIBERIUM11, "ti11", "ti11", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDTIBERIUM12(OVERLAYTD_TIBERIUM12, "ti12", "ti12", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_TIBERIUMORGOLD, false);
static OverlayType TDV12(OVERLAYTD_V12, "v12", "TEXT_STRUCTURE_TITLE_CIV12", THEATERF_TEMPERATETD, OVERLAYTYPE_NONE, false);
static OverlayType TDV13(OVERLAYTD_V13, "v13", "TEXT_STRUCTURE_TITLE_CIV12", THEATERF_TEMPERATETD, OVERLAYTYPE_NONE, false);
static OverlayType TDV14(OVERLAYTD_V14, "v14", "TEXT_STRUCTURE_TITLE_CIV13", THEATERF_TEMPERATETD | THEATERF_WINTERTD, OVERLAYTYPE_NONE, false);
static OverlayType TDV15(OVERLAYTD_V15, "v15", "TEXT_STRUCTURE_TITLE_CIV14", THEATERF_TEMPERATETD | THEATERF_WINTERTD, OVERLAYTYPE_NONE, false);
static OverlayType TDV16(OVERLAYTD_V16, "v16", "TEXT_STRUCTURE_TITLE_CIV15", THEATERF_TEMPERATETD | THEATERF_WINTERTD, OVERLAYTYPE_NONE, false);
static OverlayType TDV17(OVERLAYTD_V17, "v17", "TEXT_STRUCTURE_TITLE_CIV16", THEATERF_TEMPERATETD | THEATERF_WINTERTD, OVERLAYTYPE_NONE, false);
static OverlayType TDV18(OVERLAYTD_V18, "v18", "TEXT_STRUCTURE_TITLE_CIV17", THEATERF_TEMPERATETD | THEATERF_WINTERTD, OVERLAYTYPE_NONE, false);
static OverlayType TDFLAGSPOT(OVERLAYTD_FLAG_SPOT, "fpls", "fpls", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_FLAG, false);
static OverlayType TDWOODCRATE(OVERLAYTD_WOOD_CRATE, "wcrate", "wcrate", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_CRATE, false);
static OverlayType TDSTEELCRATE(OVERLAYTD_STEEL_CRATE, "scrate", "scrate", THEATERF_TEMPERATETD | THEATERF_WINTERTD | THEATERF_DESERTTD, OVERLAYTYPE_CRATE, false);
static OverlayType RASANDBAG(OVERLAYRA_SANDBAG_WALL, "sbag", "TEXT_STRUCTURE_RA_SBAG", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_WALL, true);
static OverlayType RACYCLONE(OVERLAYRA_CYCLONE_WALL, "cycl", "TEXT_STRUCTURE_RA_CYCL", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_WALL, true);
static OverlayType RABRICK(OVERLAYRA_BRICK_WALL, "brik", "TEXT_STRUCTURE_RA_BRIK", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_WALL, true);
static OverlayType RABARBWIRE(OVERLAYRA_BARBWIRE_WALL, "barb", "TEXT_STRUCTURE_RA_BARB", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_WALL, true);
static OverlayType RAWOOD(OVERLAYRA_WOOD_WALL, "wood", "TEXT_STRUCTURE_TD_WOOD", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_WALL, true);
static OverlayType RAGOLD1(OVERLAYRA_GOLD1, "gold01", "gold01", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_TIBERIUMORGOLD, true);
static OverlayType RAGOLD2(OVERLAYRA_GOLD2, "gold02", "gold02", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_TIBERIUMORGOLD, true);
static OverlayType RAGOLD3(OVERLAYRA_GOLD3, "gold03", "gold03", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_TIBERIUMORGOLD, true);
static OverlayType RAGOLD4(OVERLAYRA_GOLD4, "gold04", "gold04", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_TIBERIUMORGOLD, true);
static OverlayType RAGEMS1(OVERLAYRA_GEMS1, "gem01", "gem01", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_GEMS, true);
static OverlayType RAGEMS2(OVERLAYRA_GEMS2, "gem02", "gem02", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_GEMS, true);
static OverlayType RAGEMS3(OVERLAYRA_GEMS3, "gem03", "gem03", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_GEMS, true);
static OverlayType RAGEMS4(OVERLAYRA_GEMS4, "gem04", "gem04", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_GEMS, true);
static OverlayType RAV12(OVERLAYRA_V12, "v12", "TEXT_STRUCTURE_RA_CIVILIAN", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAV13(OVERLAYRA_V13, "v13", "TEXT_STRUCTURE_RA_CIVILIAN", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAV14(OVERLAYRA_V14, "v14", "TEXT_STRUCTURE_TITLE_CIV13", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAV15(OVERLAYRA_V15, "v15", "TEXT_STRUCTURE_TITLE_CIV14", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAV16(OVERLAYRA_V16, "v16", "TEXT_STRUCTURE_TITLE_CIV15", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAV17(OVERLAYRA_V17, "v17", "TEXT_STRUCTURE_TITLE_CIV16", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAV18(OVERLAYRA_V18, "v18", "TEXT_STRUCTURE_TITLE_CIV17", THEATERF_TEMPERATERA | THEATERF_SNOWRA, OVERLAYTYPE_NONE, true);
static OverlayType RAFLAGSPOT(OVERLAYRA_FLAG_SPOT, "fpls", "fpls", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_FLAG, true);
static OverlayType RAWOODCRATE(OVERLAYRA_WOOD_CRATE, "wcrate", "wcrate", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_CRATE, true);
static OverlayType RASTEELCRATE(OVERLAYRA_STEEL_CRATE, "scrate", "scrate", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_CRATE, true);
static OverlayType RAFENCE(OVERLAYRA_FENCE, "fenc", "TEXT_STRUCTURE_RA_FENC", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_WALL, true);
static OverlayType RAWATERCRATE(OVERLAYRA_WATER_CRATE, "wwcrate", "wwcrate", THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, OVERLAYTYPE_CRATE, true);
OverlayType const* const OverlayType::PointersTD[OVERLAYTD_COUNT] = {
	nullptr,
	& TDSANDBAG,
	& TDCYCLONE,
	& TDBRICK,
	& TDBARBWIRE,
	& TDWOOD,
	& TDTIBERIUM1,
	& TDTIBERIUM2,
	& TDTIBERIUM3,
	& TDTIBERIUM4,
	& TDTIBERIUM5,
	& TDTIBERIUM6,
	& TDTIBERIUM7,
	& TDTIBERIUM8,
	& TDTIBERIUM9,
	& TDTIBERIUM10,
	& TDTIBERIUM11,
	& TDTIBERIUM12,
	nullptr,
	nullptr,
	& TDV12,
	& TDV13,
	& TDV14,
	& TDV15,
	& TDV16,
	& TDV17,
	& TDV18,
	& TDFLAGSPOT,
	& TDWOODCRATE,
	& TDSTEELCRATE
};
OverlayType const* const OverlayType::PointersRA[OVERLAYRA_COUNT] = {
	& RASANDBAG,
	& RACYCLONE,
	& RABRICK,
	& RABARBWIRE,
	& RAWOOD,
	& RAGOLD1,
	& RAGOLD2,
	& RAGOLD3,
	& RAGOLD4,
	& RAGEMS1,
	& RAGEMS2,
	& RAGEMS3,
	& RAGEMS4,
	& RAV12,
	& RAV13,
	& RAV14,
	& RAV15,
	& RAV16,
	& RAV17,
	& RAV18,
	& RAFLAGSPOT,
	& RAWOODCRATE,
	& RASTEELCRATE,
	& RAFENCE,
	& RAWATERCRATE
};

void OverlayType::Init()
{
	Tile* tile;
	if (TheTilesetManager->GetTileData(Name.c_str(), 0, tile))
	{
		Thumbnail = tile->Image->Clone(Gdiplus::Rect(0, 0, tile->Image->GetWidth(), tile->Image->GetHeight()), PixelFormatDontCare);
	}
}
