#include "global.h"
#include "TemplateType.h"
#include "tileset.h"
static TemplateType TDCLEAR1(TEMPLATETD_CLEAR1, "clear1", 1, 1, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_CLEAR);
static TemplateType TDWATER(TEMPLATETD_WATER, "w1", 1, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDWATER2(TEMPLATETD_WATER2, "w2", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE1(TEMPLATETD_SHORE1, "sh1", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE2(TEMPLATETD_SHORE2, "sh2", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE3(TEMPLATETD_SHORE3, "sh3", 1, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE4(TEMPLATETD_SHORE4, "sh4", 2, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE5(TEMPLATETD_SHORE5, "sh5", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE11(TEMPLATETD_SHORE11, "sh11", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE12(TEMPLATETD_SHORE12, "sh12", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE13(TEMPLATETD_SHORE13, "sh13", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE14(TEMPLATETD_SHORE14, "sh14", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE15(TEMPLATETD_SHORE15, "sh15", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE1(TEMPLATETD_SLOPE1, "s01", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE2(TEMPLATETD_SLOPE2, "s02", 2, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE3(TEMPLATETD_SLOPE3, "s03", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE4(TEMPLATETD_SLOPE4, "s04", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE5(TEMPLATETD_SLOPE5, "s05", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE6(TEMPLATETD_SLOPE6, "s06", 2, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE7(TEMPLATETD_SLOPE7, "s07", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE8(TEMPLATETD_SLOPE8, "s08", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE9(TEMPLATETD_SLOPE9, "s09", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE10(TEMPLATETD_SLOPE10, "s10", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE11(TEMPLATETD_SLOPE11, "s11", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE12(TEMPLATETD_SLOPE12, "s12", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE13(TEMPLATETD_SLOPE13, "s13", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE14(TEMPLATETD_SLOPE14, "s14", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE15(TEMPLATETD_SLOPE15, "s15", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE16(TEMPLATETD_SLOPE16, "s16", 2, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE17(TEMPLATETD_SLOPE17, "s17", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE18(TEMPLATETD_SLOPE18, "s18", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE19(TEMPLATETD_SLOPE19, "s19", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE20(TEMPLATETD_SLOPE20, "s20", 2, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE21(TEMPLATETD_SLOPE21, "s21", 1, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE22(TEMPLATETD_SLOPE22, "s22", 2, 1, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE23(TEMPLATETD_SLOPE23, "s23", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE24(TEMPLATETD_SLOPE24, "s24", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE25(TEMPLATETD_SLOPE25, "s25", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE26(TEMPLATETD_SLOPE26, "s26", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE27(TEMPLATETD_SLOPE27, "s27", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE28(TEMPLATETD_SLOPE28, "s28", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE29(TEMPLATETD_SLOPE29, "s29", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE30(TEMPLATETD_SLOPE30, "s30", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE31(TEMPLATETD_SLOPE31, "s31", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE32(TEMPLATETD_SLOPE32, "s32", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE33(TEMPLATETD_SLOPE33, "s33", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE34(TEMPLATETD_SLOPE34, "s34", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE35(TEMPLATETD_SLOPE35, "s35", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE36(TEMPLATETD_SLOPE36, "s36", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE37(TEMPLATETD_SLOPE37, "s37", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSLOPE38(TEMPLATETD_SLOPE38, "s38", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE32(TEMPLATETD_SHORE32, "sh32", 3, 3, THEATERF_TEMPERATETD | THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE33(TEMPLATETD_SHORE33, "sh33", 3, 3, THEATERF_TEMPERATETD | THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE20(TEMPLATETD_SHORE20, "sh20", 4, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE21(TEMPLATETD_SHORE21, "sh21", 3, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE22(TEMPLATETD_SHORE22, "sh22", 6, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE23(TEMPLATETD_SHORE23, "sh23", 2, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH1(TEMPLATETD_BRUSH1, "br1", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH2(TEMPLATETD_BRUSH2, "br2", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH3(TEMPLATETD_BRUSH3, "br3", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH4(TEMPLATETD_BRUSH4, "br4", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH5(TEMPLATETD_BRUSH5, "br5", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH6(TEMPLATETD_BRUSH6, "br6", 2, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH7(TEMPLATETD_BRUSH7, "br7", 2, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH8(TEMPLATETD_BRUSH8, "br8", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH9(TEMPLATETD_BRUSH9, "br9", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRUSH10(TEMPLATETD_BRUSH10, "br10", 2, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH1(TEMPLATETD_PATCH1, "p01", 1, 1, THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH2(TEMPLATETD_PATCH2, "p02", 1, 1, THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH3(TEMPLATETD_PATCH3, "p03", 1, 1, THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH4(TEMPLATETD_PATCH4, "p04", 1, 1, THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH5(TEMPLATETD_PATCH5, "p05", 2, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH6(TEMPLATETD_PATCH6, "p06", 6, 4, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH7(TEMPLATETD_PATCH7, "p07", 4, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH8(TEMPLATETD_PATCH8, "p08", 3, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE16(TEMPLATETD_SHORE16, "sh16", 3, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE17(TEMPLATETD_SHORE17, "sh17", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE18(TEMPLATETD_SHORE18, "sh18", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE19(TEMPLATETD_SHORE19, "sh19", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH13(TEMPLATETD_PATCH13, "p13", 3, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH14(TEMPLATETD_PATCH14, "p14", 2, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH15(TEMPLATETD_PATCH15, "p15", 1, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBOULDER1(TEMPLATETD_BOULDER1, "b1", 1, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBOULDER2(TEMPLATETD_BOULDER2, "b2", 2, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD | THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBOULDER3(TEMPLATETD_BOULDER3, "b3", 3, 1, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBOULDER4(TEMPLATETD_BOULDER4, "b4", 1, 1, THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBOULDER5(TEMPLATETD_BOULDER5, "b5", 1, 1, THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBOULDER6(TEMPLATETD_BOULDER6, "b6", 1, 1, THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE6(TEMPLATETD_SHORE6, "sh6", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE7(TEMPLATETD_SHORE7, "sh7", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE8(TEMPLATETD_SHORE8, "sh8", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE9(TEMPLATETD_SHORE9, "sh9", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE10(TEMPLATETD_SHORE10, "sh10", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD1(TEMPLATETD_ROAD1, "d01", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD2(TEMPLATETD_ROAD2, "d02", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD3(TEMPLATETD_ROAD3, "d03", 1, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD4(TEMPLATETD_ROAD4, "d04", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD5(TEMPLATETD_ROAD5, "d05", 3, 4, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD6(TEMPLATETD_ROAD6, "d06", 2, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD7(TEMPLATETD_ROAD7, "d07", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD8(TEMPLATETD_ROAD8, "d08", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD9(TEMPLATETD_ROAD9, "d09", 4, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD10(TEMPLATETD_ROAD10, "d10", 4, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD11(TEMPLATETD_ROAD11, "d11", 2, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD12(TEMPLATETD_ROAD12, "d12", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD13(TEMPLATETD_ROAD13, "d13", 4, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD14(TEMPLATETD_ROAD14, "d14", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD15(TEMPLATETD_ROAD15, "d15", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD16(TEMPLATETD_ROAD16, "d16", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD17(TEMPLATETD_ROAD17, "d17", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD18(TEMPLATETD_ROAD18, "d18", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD19(TEMPLATETD_ROAD19, "d19", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD20(TEMPLATETD_ROAD20, "d20", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD21(TEMPLATETD_ROAD21, "d21", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD22(TEMPLATETD_ROAD22, "d22", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD23(TEMPLATETD_ROAD23, "d23", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD24(TEMPLATETD_ROAD24, "d24", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD25(TEMPLATETD_ROAD25, "d25", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD26(TEMPLATETD_ROAD26, "d26", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD27(TEMPLATETD_ROAD27, "d27", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD28(TEMPLATETD_ROAD28, "d28", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD29(TEMPLATETD_ROAD29, "d29", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD30(TEMPLATETD_ROAD30, "d30", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD31(TEMPLATETD_ROAD31, "d31", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD32(TEMPLATETD_ROAD32, "d32", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD33(TEMPLATETD_ROAD33, "d33", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD34(TEMPLATETD_ROAD34, "d34", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD35(TEMPLATETD_ROAD35, "d35", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD36(TEMPLATETD_ROAD36, "d36", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD37(TEMPLATETD_ROAD37, "d37", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD38(TEMPLATETD_ROAD38, "d38", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD39(TEMPLATETD_ROAD39, "d39", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD40(TEMPLATETD_ROAD40, "d40", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD41(TEMPLATETD_ROAD41, "d41", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD42(TEMPLATETD_ROAD42, "d42", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDROAD43(TEMPLATETD_ROAD43, "d43", 2, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER1(TEMPLATETD_RIVER1, "rv01", 5, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER2(TEMPLATETD_RIVER2, "rv02", 5, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER3(TEMPLATETD_RIVER3, "rv03", 4, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER4(TEMPLATETD_RIVER4, "rv04", 4, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER5(TEMPLATETD_RIVER5, "rv05", 3, 3, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER6(TEMPLATETD_RIVER6, "rv06", 3, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER7(TEMPLATETD_RIVER7, "rv07", 3, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER8(TEMPLATETD_RIVER8, "rv08", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER9(TEMPLATETD_RIVER9, "rv09", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER10(TEMPLATETD_RIVER10, "rv10", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER11(TEMPLATETD_RIVER11, "rv11", 2, 2, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER12(TEMPLATETD_RIVER12, "rv12", 3, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER13(TEMPLATETD_RIVER13, "rv13", 4, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER14(TEMPLATETD_RIVER14, "rv14", 4, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER15(TEMPLATETD_RIVER15, "rv15", 4, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER16(TEMPLATETD_RIVER16, "rv16", 6, 4, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER17(TEMPLATETD_RIVER17, "rv17", 6, 5, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER18(TEMPLATETD_RIVER18, "rv18", 4, 4, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER19(TEMPLATETD_RIVER19, "rv19", 4, 4, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER20(TEMPLATETD_RIVER20, "rv20", 6, 8, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER21(TEMPLATETD_RIVER21, "rv21", 5, 8, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER22(TEMPLATETD_RIVER22, "rv22", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER23(TEMPLATETD_RIVER23, "rv23", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER24(TEMPLATETD_RIVER24, "rv24", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDRIVER25(TEMPLATETD_RIVER25, "rv25", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDFORD1(TEMPLATETD_FORD1, "ford1", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDFORD2(TEMPLATETD_FORD2, "ford2", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDFALLS1(TEMPLATETD_FALLS1, "falls1", 3, 3, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDFALLS2(TEMPLATETD_FALLS2, "falls2", 3, 2, THEATERF_WINTERTD | THEATERF_DESERTTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE1(TEMPLATETD_BRIDGE1, "bridge1", 4, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE1D(TEMPLATETD_BRIDGE1D, "bridge1d", 4, 4, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE2(TEMPLATETD_BRIDGE2, "bridge2", 5, 5, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE2D(TEMPLATETD_BRIDGE2D, "bridge2d", 5, 5, THEATERF_WINTERTD | THEATERF_TEMPERATETD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE3(TEMPLATETD_BRIDGE3, "bridge3", 6, 5, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE3D(TEMPLATETD_BRIDGE3D, "bridge3d", 6, 5, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE4(TEMPLATETD_BRIDGE4, "bridge4", 6, 4, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDBRIDGE4D(TEMPLATETD_BRIDGE4D, "bridge4d", 6, 4, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE24(TEMPLATETD_SHORE24, "sh24", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE25(TEMPLATETD_SHORE25, "sh25", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE26(TEMPLATETD_SHORE26, "sh26", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE27(TEMPLATETD_SHORE27, "sh27", 4, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE28(TEMPLATETD_SHORE28, "sh28", 3, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE29(TEMPLATETD_SHORE29, "sh29", 6, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE30(TEMPLATETD_SHORE30, "sh30", 2, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE31(TEMPLATETD_SHORE31, "sh31", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH16(TEMPLATETD_PATCH16, "p16", 2, 2, THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH17(TEMPLATETD_PATCH17, "p17", 4, 2, THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH18(TEMPLATETD_PATCH18, "p18", 4, 3, THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH19(TEMPLATETD_PATCH19, "p19", 4, 3, THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDPATCH20(TEMPLATETD_PATCH20, "p20", 4, 3, THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE34(TEMPLATETD_SHORE34, "sh34", 3, 3, THEATERF_TEMPERATETD | THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE35(TEMPLATETD_SHORE35, "sh35", 3, 3, THEATERF_TEMPERATETD | THEATERF_WINTERTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE36(TEMPLATETD_SHORE36, "sh36", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE37(TEMPLATETD_SHORE37, "sh37", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE38(TEMPLATETD_SHORE38, "sh38", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE39(TEMPLATETD_SHORE39, "sh39", 1, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE40(TEMPLATETD_SHORE40, "sh40", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE41(TEMPLATETD_SHORE41, "sh41", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE42(TEMPLATETD_SHORE42, "sh42", 1, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE43(TEMPLATETD_SHORE43, "sh43", 1, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE44(TEMPLATETD_SHORE44, "sh44", 1, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE45(TEMPLATETD_SHORE45, "sh45", 1, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE46(TEMPLATETD_SHORE46, "sh46", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE47(TEMPLATETD_SHORE47, "sh47", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE48(TEMPLATETD_SHORE48, "sh48", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE49(TEMPLATETD_SHORE49, "sh49", 3, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE50(TEMPLATETD_SHORE50, "sh50", 4, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE51(TEMPLATETD_SHORE51, "sh51", 4, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE52(TEMPLATETD_SHORE52, "sh52", 4, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE53(TEMPLATETD_SHORE53, "sh53", 4, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE54(TEMPLATETD_SHORE54, "sh54", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE55(TEMPLATETD_SHORE55, "sh55", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE56(TEMPLATETD_SHORE56, "sh56", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE57(TEMPLATETD_SHORE57, "sh57", 3, 2, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE58(TEMPLATETD_SHORE58, "sh58", 2, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE59(TEMPLATETD_SHORE59, "sh59", 2, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE60(TEMPLATETD_SHORE60, "sh60", 2, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE61(TEMPLATETD_SHORE61, "sh61", 2, 3, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE62(TEMPLATETD_SHORE62, "sh62", 6, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);
static TemplateType TDSHORE63(TEMPLATETD_SHORE63, "sh63", 4, 1, THEATERF_DESERTTD, TEMPLATETYPE_NONE);

TemplateType * const TemplateType::PointersTD[TEMPLATETD_COUNT] = {
	& TDCLEAR1,
	& TDWATER,
	& TDWATER2,
	& TDSHORE1,
	& TDSHORE2,
	& TDSHORE3,
	& TDSHORE4,
	& TDSHORE5,
	& TDSHORE11,
	& TDSHORE12,
	& TDSHORE13,
	& TDSHORE14,
	& TDSHORE15,
	& TDSLOPE1,
	& TDSLOPE2,
	& TDSLOPE3,
	& TDSLOPE4,
	& TDSLOPE5,
	& TDSLOPE6,
	& TDSLOPE7,
	& TDSLOPE8,
	& TDSLOPE9,
	& TDSLOPE10,
	& TDSLOPE11,
	& TDSLOPE12,
	& TDSLOPE13,
	& TDSLOPE14,
	& TDSLOPE15,
	& TDSLOPE16,
	& TDSLOPE17,
	& TDSLOPE18,
	& TDSLOPE19,
	& TDSLOPE20,
	& TDSLOPE21,
	& TDSLOPE22,
	& TDSLOPE23,
	& TDSLOPE24,
	& TDSLOPE25,
	& TDSLOPE26,
	& TDSLOPE27,
	& TDSLOPE28,
	& TDSLOPE29,
	& TDSLOPE30,
	& TDSLOPE31,
	& TDSLOPE32,
	& TDSLOPE33,
	& TDSLOPE34,
	& TDSLOPE35,
	& TDSLOPE36,
	& TDSLOPE37,
	& TDSLOPE38,
	& TDSHORE32,
	& TDSHORE33,
	& TDSHORE20,
	& TDSHORE21,
	& TDSHORE22,
	& TDSHORE23,
	& TDBRUSH1,
	& TDBRUSH2,
	& TDBRUSH3,
	& TDBRUSH4,
	& TDBRUSH5,
	& TDBRUSH6,
	& TDBRUSH7,
	& TDBRUSH8,
	& TDBRUSH9,
	& TDBRUSH10,
	& TDPATCH1,
	& TDPATCH2,
	& TDPATCH3,
	& TDPATCH4,
	& TDPATCH5,
	& TDPATCH6,
	& TDPATCH7,
	& TDPATCH8,
	& TDSHORE16,
	& TDSHORE17,
	& TDSHORE18,
	& TDSHORE19,
	& TDPATCH13,
	& TDPATCH14,
	& TDPATCH15,
	& TDBOULDER1,
	& TDBOULDER2,
	& TDBOULDER3,
	& TDBOULDER4,
	& TDBOULDER5,
	& TDBOULDER6,
	& TDSHORE6,
	& TDSHORE7,
	& TDSHORE8,
	& TDSHORE9,
	& TDSHORE10,
	& TDROAD1,
	& TDROAD2,
	& TDROAD3,
	& TDROAD4,
	& TDROAD5,
	& TDROAD6,
	& TDROAD7,
	& TDROAD8,
	& TDROAD9,
	& TDROAD10,
	& TDROAD11,
	& TDROAD12,
	& TDROAD13,
	& TDROAD14,
	& TDROAD15,
	& TDROAD16,
	& TDROAD17,
	& TDROAD18,
	& TDROAD19,
	& TDROAD20,
	& TDROAD21,
	& TDROAD22,
	& TDROAD23,
	& TDROAD24,
	& TDROAD25,
	& TDROAD26,
	& TDROAD27,
	& TDROAD28,
	& TDROAD29,
	& TDROAD30,
	& TDROAD31,
	& TDROAD32,
	& TDROAD33,
	& TDROAD34,
	& TDROAD35,
	& TDROAD36,
	& TDROAD37,
	& TDROAD38,
	& TDROAD39,
	& TDROAD40,
	& TDROAD41,
	& TDROAD42,
	& TDROAD43,
	& TDRIVER1,
	& TDRIVER2,
	& TDRIVER3,
	& TDRIVER4,
	& TDRIVER5,
	& TDRIVER6,
	& TDRIVER7,
	& TDRIVER8,
	& TDRIVER9,
	& TDRIVER10,
	& TDRIVER11,
	& TDRIVER12,
	& TDRIVER13,
	& TDRIVER14,
	& TDRIVER15,
	& TDRIVER16,
	& TDRIVER17,
	& TDRIVER18,
	& TDRIVER19,
	& TDRIVER20,
	& TDRIVER21,
	& TDRIVER22,
	& TDRIVER23,
	& TDRIVER24,
	& TDRIVER25,
	& TDFORD1,
	& TDFORD2,
	& TDFALLS1,
	& TDFALLS2,
	& TDBRIDGE1,
	& TDBRIDGE1D,
	& TDBRIDGE2,
	& TDBRIDGE2D,
	& TDBRIDGE3,
	& TDBRIDGE3D,
	& TDBRIDGE4,
	& TDBRIDGE4D,
	& TDSHORE24,
	& TDSHORE25,
	& TDSHORE26,
	& TDSHORE27,
	& TDSHORE28,
	& TDSHORE29,
	& TDSHORE30,
	& TDSHORE31,
	& TDPATCH16,
	& TDPATCH17,
	& TDPATCH18,
	& TDPATCH19,
	& TDPATCH20,
	& TDSHORE34,
	& TDSHORE35,
	& TDSHORE36,
	& TDSHORE37,
	& TDSHORE38,
	& TDSHORE39,
	& TDSHORE40,
	& TDSHORE41,
	& TDSHORE42,
	& TDSHORE43,
	& TDSHORE44,
	& TDSHORE45,
	& TDSHORE46,
	& TDSHORE47,
	& TDSHORE48,
	& TDSHORE49,
	& TDSHORE50,
	& TDSHORE51,
	& TDSHORE52,
	& TDSHORE53,
	& TDSHORE54,
	& TDSHORE55,
	& TDSHORE56,
	& TDSHORE57,
	& TDSHORE58,
	& TDSHORE59,
	& TDSHORE60,
	& TDSHORE61,
	& TDSHORE62,
	& TDSHORE63,
};

static TemplateType RACLEAR1(TEMPLATERA_CLEAR1, "clear1", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA | THEATERF_INTERIORRA, TEMPLATETYPE_CLEAR);
static TemplateType RAWATER(TEMPLATERA_WATER, "w1", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_WATER);
static TemplateType RAWATER2(TEMPLATERA_WATER2, "w2", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_WATER);
static TemplateType RASHORE01(TEMPLATERA_SHORE01, "sh01", 4, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE02(TEMPLATERA_SHORE02, "sh02", 5, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE03(TEMPLATERA_SHORE03, "sh03", 3, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE04(TEMPLATERA_SHORE04, "sh04", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE05(TEMPLATERA_SHORE05, "sh05", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE06(TEMPLATERA_SHORE06, "sh06", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE07(TEMPLATERA_SHORE07, "sh07", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE08(TEMPLATERA_SHORE08, "sh08", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE09(TEMPLATERA_SHORE09, "sh09", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE10(TEMPLATERA_SHORE10, "sh10", 5, 6, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE11(TEMPLATERA_SHORE11, "sh11", 4, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE12(TEMPLATERA_SHORE12, "sh12", 3, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE13(TEMPLATERA_SHORE13, "sh13", 6, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE14(TEMPLATERA_SHORE14, "sh14", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE15(TEMPLATERA_SHORE15, "sh15", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE16(TEMPLATERA_SHORE16, "sh16", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE17(TEMPLATERA_SHORE17, "sh17", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE18(TEMPLATERA_SHORE18, "sh18", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE19(TEMPLATERA_SHORE19, "sh19", 4, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE20(TEMPLATERA_SHORE20, "sh20", 5, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE21(TEMPLATERA_SHORE21, "sh21", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE22(TEMPLATERA_SHORE22, "sh22", 6, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE23(TEMPLATERA_SHORE23, "sh23", 5, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE24(TEMPLATERA_SHORE24, "sh24", 3, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE25(TEMPLATERA_SHORE25, "sh25", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE26(TEMPLATERA_SHORE26, "sh26", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE27(TEMPLATERA_SHORE27, "sh27", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE28(TEMPLATERA_SHORE28, "sh28", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE29(TEMPLATERA_SHORE29, "sh29", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE30(TEMPLATERA_SHORE30, "sh30", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE31(TEMPLATERA_SHORE31, "sh31", 6, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE32(TEMPLATERA_SHORE32, "sh32", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE33(TEMPLATERA_SHORE33, "sh33", 3, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE34(TEMPLATERA_SHORE34, "sh34", 6, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE35(TEMPLATERA_SHORE35, "sh35", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE36(TEMPLATERA_SHORE36, "sh36", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE37(TEMPLATERA_SHORE37, "sh37", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE38(TEMPLATERA_SHORE38, "sh38", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE39(TEMPLATERA_SHORE39, "sh39", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE40(TEMPLATERA_SHORE40, "sh40", 5, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE41(TEMPLATERA_SHORE41, "sh41", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE42(TEMPLATERA_SHORE42, "sh42", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE43(TEMPLATERA_SHORE43, "sh43", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE44(TEMPLATERA_SHORE44, "sh44", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE45(TEMPLATERA_SHORE45, "sh45", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE46(TEMPLATERA_SHORE46, "sh46", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE47(TEMPLATERA_SHORE47, "sh47", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE48(TEMPLATERA_SHORE48, "sh48", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE49(TEMPLATERA_SHORE49, "sh49", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE50(TEMPLATERA_SHORE50, "sh50", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE51(TEMPLATERA_SHORE51, "sh51", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE52(TEMPLATERA_SHORE52, "sh52", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE53(TEMPLATERA_SHORE53, "sh53", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE54(TEMPLATERA_SHORE54, "sh54", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE55(TEMPLATERA_SHORE55, "sh55", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORE56(TEMPLATERA_SHORE56, "sh56", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF01(TEMPLATERA_SHORECLIFF01, "wc01", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF02(TEMPLATERA_SHORECLIFF02, "wc02", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF03(TEMPLATERA_SHORECLIFF03, "wc03", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF04(TEMPLATERA_SHORECLIFF04, "wc04", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF05(TEMPLATERA_SHORECLIFF05, "wc05", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF06(TEMPLATERA_SHORECLIFF06, "wc06", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF07(TEMPLATERA_SHORECLIFF07, "wc07", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF08(TEMPLATERA_SHORECLIFF08, "wc08", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF09(TEMPLATERA_SHORECLIFF09, "wc09", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF10(TEMPLATERA_SHORECLIFF10, "wc10", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF11(TEMPLATERA_SHORECLIFF11, "wc11", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF12(TEMPLATERA_SHORECLIFF12, "wc12", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF13(TEMPLATERA_SHORECLIFF13, "wc13", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF14(TEMPLATERA_SHORECLIFF14, "wc14", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF15(TEMPLATERA_SHORECLIFF15, "wc15", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF16(TEMPLATERA_SHORECLIFF16, "wc16", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF17(TEMPLATERA_SHORECLIFF17, "wc17", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF18(TEMPLATERA_SHORECLIFF18, "wc18", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF19(TEMPLATERA_SHORECLIFF19, "wc19", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF20(TEMPLATERA_SHORECLIFF20, "wc20", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF21(TEMPLATERA_SHORECLIFF21, "wc21", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF22(TEMPLATERA_SHORECLIFF22, "wc22", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF23(TEMPLATERA_SHORECLIFF23, "wc23", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF24(TEMPLATERA_SHORECLIFF24, "wc24", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF25(TEMPLATERA_SHORECLIFF25, "wc25", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF26(TEMPLATERA_SHORECLIFF26, "wc26", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF27(TEMPLATERA_SHORECLIFF27, "wc27", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF28(TEMPLATERA_SHORECLIFF28, "wc28", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF29(TEMPLATERA_SHORECLIFF29, "wc29", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF30(TEMPLATERA_SHORECLIFF30, "wc30", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF31(TEMPLATERA_SHORECLIFF31, "wc31", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF32(TEMPLATERA_SHORECLIFF32, "wc32", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF33(TEMPLATERA_SHORECLIFF33, "wc33", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF34(TEMPLATERA_SHORECLIFF34, "wc34", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF35(TEMPLATERA_SHORECLIFF35, "wc35", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF36(TEMPLATERA_SHORECLIFF36, "wc36", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF37(TEMPLATERA_SHORECLIFF37, "wc37", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASHORECLIFF38(TEMPLATERA_SHORECLIFF38, "wc38", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABOULDER1(TEMPLATERA_BOULDER1, "b1", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABOULDER2(TEMPLATERA_BOULDER2, "b2", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABOULDER3(TEMPLATERA_BOULDER3, "b3", 3, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH01(TEMPLATERA_PATCH01, "p01", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH02(TEMPLATERA_PATCH02, "p02", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH03(TEMPLATERA_PATCH03, "p03", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH04(TEMPLATERA_PATCH04, "p04", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH07(TEMPLATERA_PATCH07, "p07", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH08(TEMPLATERA_PATCH08, "p08", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH13(TEMPLATERA_PATCH13, "p13", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAPATCH14(TEMPLATERA_PATCH14, "p14", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER01(TEMPLATERA_RIVER01, "rv01", 5, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER02(TEMPLATERA_RIVER02, "rv02", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER03(TEMPLATERA_RIVER03, "rv03", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER04(TEMPLATERA_RIVER04, "rv04", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER05(TEMPLATERA_RIVER05, "rv05", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER06(TEMPLATERA_RIVER06, "rv06", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER07(TEMPLATERA_RIVER07, "rv07", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER08(TEMPLATERA_RIVER08, "rv08", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER09(TEMPLATERA_RIVER09, "rv09", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER10(TEMPLATERA_RIVER10, "rv10", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER11(TEMPLATERA_RIVER11, "rv11", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER12(TEMPLATERA_RIVER12, "rv12", 3, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER13(TEMPLATERA_RIVER13, "rv13", 4, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAFALLS1(TEMPLATERA_FALLS1, "falls1", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAFALLS1A(TEMPLATERA_FALLS1A, "falls1a", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAFALLS2(TEMPLATERA_FALLS2, "falls2", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAFALLS2A(TEMPLATERA_FALLS2A, "falls2a", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAFORD1(TEMPLATERA_FORD1, "ford1", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAFORD2(TEMPLATERA_FORD2, "ford2", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1(TEMPLATERA_BRIDGE1, "bridge1", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1D(TEMPLATERA_BRIDGE1D, "bridge1d", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2(TEMPLATERA_BRIDGE2, "bridge2", 5, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2D(TEMPLATERA_BRIDGE2D, "bridge2d", 5, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE01(TEMPLATERA_SLOPE01, "s01", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE02(TEMPLATERA_SLOPE02, "s02", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE03(TEMPLATERA_SLOPE03, "s03", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE04(TEMPLATERA_SLOPE04, "s04", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE05(TEMPLATERA_SLOPE05, "s05", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE06(TEMPLATERA_SLOPE06, "s06", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE07(TEMPLATERA_SLOPE07, "s07", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE08(TEMPLATERA_SLOPE08, "s08", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE09(TEMPLATERA_SLOPE09, "s09", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE10(TEMPLATERA_SLOPE10, "s10", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE11(TEMPLATERA_SLOPE11, "s11", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE12(TEMPLATERA_SLOPE12, "s12", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE13(TEMPLATERA_SLOPE13, "s13", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE14(TEMPLATERA_SLOPE14, "s14", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE15(TEMPLATERA_SLOPE15, "s15", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE16(TEMPLATERA_SLOPE16, "s16", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE17(TEMPLATERA_SLOPE17, "s17", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE18(TEMPLATERA_SLOPE18, "s18", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE19(TEMPLATERA_SLOPE19, "s19", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE20(TEMPLATERA_SLOPE20, "s20", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE21(TEMPLATERA_SLOPE21, "s21", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE22(TEMPLATERA_SLOPE22, "s22", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE23(TEMPLATERA_SLOPE23, "s23", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE24(TEMPLATERA_SLOPE24, "s24", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE25(TEMPLATERA_SLOPE25, "s25", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE26(TEMPLATERA_SLOPE26, "s26", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE27(TEMPLATERA_SLOPE27, "s27", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE28(TEMPLATERA_SLOPE28, "s28", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE29(TEMPLATERA_SLOPE29, "s29", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE30(TEMPLATERA_SLOPE30, "s30", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE31(TEMPLATERA_SLOPE31, "s31", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE32(TEMPLATERA_SLOPE32, "s32", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE33(TEMPLATERA_SLOPE33, "s33", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE34(TEMPLATERA_SLOPE34, "s34", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE35(TEMPLATERA_SLOPE35, "s35", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE36(TEMPLATERA_SLOPE36, "s36", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE37(TEMPLATERA_SLOPE37, "s37", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RASLOPE38(TEMPLATERA_SLOPE38, "s38", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD01(TEMPLATERA_ROAD01, "d01", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD02(TEMPLATERA_ROAD02, "d02", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD03(TEMPLATERA_ROAD03, "d03", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD04(TEMPLATERA_ROAD04, "d04", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD05(TEMPLATERA_ROAD05, "d05", 3, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD06(TEMPLATERA_ROAD06, "d06", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD07(TEMPLATERA_ROAD07, "d07", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD08(TEMPLATERA_ROAD08, "d08", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD09(TEMPLATERA_ROAD09, "d09", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD10(TEMPLATERA_ROAD10, "d10", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD11(TEMPLATERA_ROAD11, "d11", 2, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD12(TEMPLATERA_ROAD12, "d12", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD13(TEMPLATERA_ROAD13, "d13", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD14(TEMPLATERA_ROAD14, "d14", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD15(TEMPLATERA_ROAD15, "d15", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD16(TEMPLATERA_ROAD16, "d16", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD17(TEMPLATERA_ROAD17, "d17", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD18(TEMPLATERA_ROAD18, "d18", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD19(TEMPLATERA_ROAD19, "d19", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD20(TEMPLATERA_ROAD20, "d20", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD21(TEMPLATERA_ROAD21, "d21", 3, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD22(TEMPLATERA_ROAD22, "d22", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD23(TEMPLATERA_ROAD23, "d23", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD24(TEMPLATERA_ROAD24, "d24", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD25(TEMPLATERA_ROAD25, "d25", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD26(TEMPLATERA_ROAD26, "d26", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD27(TEMPLATERA_ROAD27, "d27", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD28(TEMPLATERA_ROAD28, "d28", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD29(TEMPLATERA_ROAD29, "d29", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD30(TEMPLATERA_ROAD30, "d30", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD31(TEMPLATERA_ROAD31, "d31", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD32(TEMPLATERA_ROAD32, "d32", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD33(TEMPLATERA_ROAD33, "d33", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD34(TEMPLATERA_ROAD34, "d34", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD35(TEMPLATERA_ROAD35, "d35", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD36(TEMPLATERA_ROAD36, "d36", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD37(TEMPLATERA_ROAD37, "d37", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD38(TEMPLATERA_ROAD38, "d38", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD39(TEMPLATERA_ROAD39, "d39", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD40(TEMPLATERA_ROAD40, "d40", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD41(TEMPLATERA_ROAD41, "d41", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD42(TEMPLATERA_ROAD42, "d42", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD43(TEMPLATERA_ROAD43, "d43", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH01(TEMPLATERA_ROUGH01, "rf01", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH02(TEMPLATERA_ROUGH02, "rf02", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH03(TEMPLATERA_ROUGH03, "rf03", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH04(TEMPLATERA_ROUGH04, "rf04", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH05(TEMPLATERA_ROUGH05, "rf05", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH06(TEMPLATERA_ROUGH06, "rf06", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH07(TEMPLATERA_ROUGH07, "rf07", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH08(TEMPLATERA_ROUGH08, "rf08", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH09(TEMPLATERA_ROUGH09, "rf09", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH10(TEMPLATERA_ROUGH10, "rf10", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROUGH11(TEMPLATERA_ROUGH11, "rf11", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD44(TEMPLATERA_ROAD44, "d44", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAROAD45(TEMPLATERA_ROAD45, "d45", 1, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER14(TEMPLATERA_RIVER14, "rv14", 1, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVER15(TEMPLATERA_RIVER15, "rv15", 2, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVERCLIFF01(TEMPLATERA_RIVERCLIFF01, "rc01", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVERCLIFF02(TEMPLATERA_RIVERCLIFF02, "rc02", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVERCLIFF03(TEMPLATERA_RIVERCLIFF03, "rc03", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RARIVERCLIFF04(TEMPLATERA_RIVERCLIFF04, "rc04", 2, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1A(TEMPLATERA_BRIDGE_1A, "br1a", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1B(TEMPLATERA_BRIDGE_1B, "br1b", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1C(TEMPLATERA_BRIDGE_1C, "br1c", 4, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2A(TEMPLATERA_BRIDGE_2A, "br2a", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2B(TEMPLATERA_BRIDGE_2B, "br2b", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2C(TEMPLATERA_BRIDGE_2C, "br2c", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE3A(TEMPLATERA_BRIDGE_3A, "br3a", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE3B(TEMPLATERA_BRIDGE_3B, "br3b", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE3C(TEMPLATERA_BRIDGE_3C, "br3c", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE3D(TEMPLATERA_BRIDGE_3D, "br3d", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE3E(TEMPLATERA_BRIDGE_3E, "br3e", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE3F(TEMPLATERA_BRIDGE_3F, "br3f", 4, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAF01(TEMPLATERA_F01, "f01", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAF02(TEMPLATERA_F02, "f02", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAF03(TEMPLATERA_F03, "f03", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAF04(TEMPLATERA_F04, "f04", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAF05(TEMPLATERA_F05, "f05", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAF06(TEMPLATERA_F06, "f06", 3, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0001(TEMPLATERA_ARRO0001, "arro0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0002(TEMPLATERA_ARRO0002, "arro0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0003(TEMPLATERA_ARRO0003, "arro0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0004(TEMPLATERA_ARRO0004, "arro0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0005(TEMPLATERA_ARRO0005, "arro0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0006(TEMPLATERA_ARRO0006, "arro0006", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0007(TEMPLATERA_ARRO0007, "arro0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0008(TEMPLATERA_ARRO0008, "arro0008", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0009(TEMPLATERA_ARRO0009, "arro0009", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0010(TEMPLATERA_ARRO0010, "arro0010", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0011(TEMPLATERA_ARRO0011, "arro0011", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0012(TEMPLATERA_ARRO0012, "arro0012", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0013(TEMPLATERA_ARRO0013, "arro0013", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0014(TEMPLATERA_ARRO0014, "arro0014", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAARRO0015(TEMPLATERA_ARRO0015, "arro0015", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0001(TEMPLATERA_FLOR0001, "flor0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0002(TEMPLATERA_FLOR0002, "flor0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0003(TEMPLATERA_FLOR0003, "flor0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0004(TEMPLATERA_FLOR0004, "flor0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0005(TEMPLATERA_FLOR0005, "flor0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0006(TEMPLATERA_FLOR0006, "flor0006", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAFLOR0007(TEMPLATERA_FLOR0007, "flor0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGFLR0001(TEMPLATERA_GFLR0001, "gflr0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGFLR0002(TEMPLATERA_GFLR0002, "gflr0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGFLR0003(TEMPLATERA_GFLR0003, "gflr0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGFLR0004(TEMPLATERA_GFLR0004, "gflr0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGFLR0005(TEMPLATERA_GFLR0005, "gflr0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0001(TEMPLATERA_GSTR0001, "gstr0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0002(TEMPLATERA_GSTR0002, "gstr0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0003(TEMPLATERA_GSTR0003, "gstr0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0004(TEMPLATERA_GSTR0004, "gstr0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0005(TEMPLATERA_GSTR0005, "gstr0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0006(TEMPLATERA_GSTR0006, "gstr0006", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0007(TEMPLATERA_GSTR0007, "gstr0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0008(TEMPLATERA_GSTR0008, "gstr0008", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0009(TEMPLATERA_GSTR0009, "gstr0009", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0010(TEMPLATERA_GSTR0010, "gstr0010", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAGSTR0011(TEMPLATERA_GSTR0011, "gstr0011", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0001(TEMPLATERA_LWAL0001, "lwal0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0002(TEMPLATERA_LWAL0002, "lwal0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0003(TEMPLATERA_LWAL0003, "lwal0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0004(TEMPLATERA_LWAL0004, "lwal0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0005(TEMPLATERA_LWAL0005, "lwal0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0006(TEMPLATERA_LWAL0006, "lwal0006", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0007(TEMPLATERA_LWAL0007, "lwal0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0008(TEMPLATERA_LWAL0008, "lwal0008", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0009(TEMPLATERA_LWAL0009, "lwal0009", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0010(TEMPLATERA_LWAL0010, "lwal0010", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0011(TEMPLATERA_LWAL0011, "lwal0011", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0012(TEMPLATERA_LWAL0012, "lwal0012", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0013(TEMPLATERA_LWAL0013, "lwal0013", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0014(TEMPLATERA_LWAL0014, "lwal0014", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0015(TEMPLATERA_LWAL0015, "lwal0015", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0016(TEMPLATERA_LWAL0016, "lwal0016", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0017(TEMPLATERA_LWAL0017, "lwal0017", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0018(TEMPLATERA_LWAL0018, "lwal0018", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0019(TEMPLATERA_LWAL0019, "lwal0019", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0020(TEMPLATERA_LWAL0020, "lwal0020", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0021(TEMPLATERA_LWAL0021, "lwal0021", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0022(TEMPLATERA_LWAL0022, "lwal0022", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0023(TEMPLATERA_LWAL0023, "lwal0023", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0024(TEMPLATERA_LWAL0024, "lwal0024", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0025(TEMPLATERA_LWAL0025, "lwal0025", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0026(TEMPLATERA_LWAL0026, "lwal0026", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RALWAL0027(TEMPLATERA_LWAL0027, "lwal0027", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0001(TEMPLATERA_STRP0001, "strp0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0002(TEMPLATERA_STRP0002, "strp0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0003(TEMPLATERA_STRP0003, "strp0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0004(TEMPLATERA_STRP0004, "strp0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0005(TEMPLATERA_STRP0005, "strp0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0006(TEMPLATERA_STRP0006, "strp0006", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0007(TEMPLATERA_STRP0007, "strp0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0008(TEMPLATERA_STRP0008, "strp0008", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0009(TEMPLATERA_STRP0009, "strp0009", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0010(TEMPLATERA_STRP0010, "strp0010", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RASTRP0011(TEMPLATERA_STRP0011, "strp0011", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0001(TEMPLATERA_WALL0001, "wall0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0002(TEMPLATERA_WALL0002, "wall0002", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0003(TEMPLATERA_WALL0003, "wall0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0004(TEMPLATERA_WALL0004, "wall0004", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0005(TEMPLATERA_WALL0005, "wall0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0006(TEMPLATERA_WALL0006, "wall0006", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0007(TEMPLATERA_WALL0007, "wall0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0008(TEMPLATERA_WALL0008, "wall0008", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0009(TEMPLATERA_WALL0009, "wall0009", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0010(TEMPLATERA_WALL0010, "wall0010", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0011(TEMPLATERA_WALL0011, "wall0011", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0012(TEMPLATERA_WALL0012, "wall0012", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0013(TEMPLATERA_WALL0013, "wall0013", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0014(TEMPLATERA_WALL0014, "wall0014", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0015(TEMPLATERA_WALL0015, "wall0015", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0016(TEMPLATERA_WALL0016, "wall0016", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0017(TEMPLATERA_WALL0017, "wall0017", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0018(TEMPLATERA_WALL0018, "wall0018", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0019(TEMPLATERA_WALL0019, "wall0019", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0020(TEMPLATERA_WALL0020, "wall0020", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0021(TEMPLATERA_WALL0021, "wall0021", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0022(TEMPLATERA_WALL0022, "wall0022", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0023(TEMPLATERA_WALL0023, "wall0023", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0024(TEMPLATERA_WALL0024, "wall0024", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0025(TEMPLATERA_WALL0025, "wall0025", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0026(TEMPLATERA_WALL0026, "wall0026", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0027(TEMPLATERA_WALL0027, "wall0027", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0028(TEMPLATERA_WALL0028, "wall0028", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0029(TEMPLATERA_WALL0029, "wall0029", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0030(TEMPLATERA_WALL0030, "wall0030", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0031(TEMPLATERA_WALL0031, "wall0031", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0032(TEMPLATERA_WALL0032, "wall0032", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0033(TEMPLATERA_WALL0033, "wall0033", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0034(TEMPLATERA_WALL0034, "wall0034", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0035(TEMPLATERA_WALL0035, "wall0035", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0036(TEMPLATERA_WALL0036, "wall0036", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0037(TEMPLATERA_WALL0037, "wall0037", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0038(TEMPLATERA_WALL0038, "wall0038", 2, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0039(TEMPLATERA_WALL0039, "wall0039", 2, 3, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0040(TEMPLATERA_WALL0040, "wall0040", 2, 3, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0041(TEMPLATERA_WALL0041, "wall0041", 2, 3, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0042(TEMPLATERA_WALL0042, "wall0042", 2, 3, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0043(TEMPLATERA_WALL0043, "wall0043", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0044(TEMPLATERA_WALL0044, "wall0044", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0045(TEMPLATERA_WALL0045, "wall0045", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0046(TEMPLATERA_WALL0046, "wall0046", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0047(TEMPLATERA_WALL0047, "wall0047", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0048(TEMPLATERA_WALL0048, "wall0048", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAWALL0049(TEMPLATERA_WALL0049, "wall0049", 3, 3, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1H(TEMPLATERA_BRIDGE1H, "bridge1h", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2H(TEMPLATERA_BRIDGE2H, "bridge2h", 5, 2, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1AX(TEMPLATERA_BRIDGE_1AX, "br1x", 5, 3, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2AX(TEMPLATERA_BRIDGE_2AX, "br2x", 5, 1, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE1X(TEMPLATERA_BRIDGE1X, "bridge1x", 5, 4, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RABRIDGE2X(TEMPLATERA_BRIDGE2X, "bridge2x", 5, 5, THEATERF_TEMPERATERA | THEATERF_SNOWRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0001(TEMPLATERA_XTRA0001, "xtra0001", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0002(TEMPLATERA_XTRA0002, "xtra0002", 2, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0003(TEMPLATERA_XTRA0003, "xtra0003", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0004(TEMPLATERA_XTRA0004, "xtra0004", 1, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0005(TEMPLATERA_XTRA0005, "xtra0005", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0006(TEMPLATERA_XTRA0006, "xtra0006", 2, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0007(TEMPLATERA_XTRA0007, "xtra0007", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0008(TEMPLATERA_XTRA0008, "xtra0008", 1, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0009(TEMPLATERA_XTRA0009, "xtra0009", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0010(TEMPLATERA_XTRA0010, "xtra0010", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0011(TEMPLATERA_XTRA0011, "xtra0011", 1, 1, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0012(TEMPLATERA_XTRA0012, "xtra0012", 1, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0013(TEMPLATERA_XTRA0013, "xtra0013", 1, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0014(TEMPLATERA_XTRA0014, "xtra0014", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0015(TEMPLATERA_XTRA0015, "xtra0015", 3, 2, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAXTRA0016(TEMPLATERA_XTRA0016, "xtra0016", 2, 4, THEATERF_INTERIORRA, TEMPLATETYPE_NONE);
static TemplateType RAHILL01(TEMPLATERA_HILL01, "hill01", 4, 3, THEATERF_TEMPERATERA, TEMPLATETYPE_NONE);

TemplateType * const TemplateType::PointersRA[TEMPLATERA_COUNT] = {
	& RACLEAR1,
	& RAWATER,
	& RAWATER2,
	& RASHORE01,
	& RASHORE02,
	& RASHORE03,
	& RASHORE04,
	& RASHORE05,
	& RASHORE06,
	& RASHORE07,
	& RASHORE08,
	& RASHORE09,
	& RASHORE10,
	& RASHORE11,
	& RASHORE12,
	& RASHORE13,
	& RASHORE14,
	& RASHORE15,
	& RASHORE16,
	& RASHORE17,
	& RASHORE18,
	& RASHORE19,
	& RASHORE20,
	& RASHORE21,
	& RASHORE22,
	& RASHORE23,
	& RASHORE24,
	& RASHORE25,
	& RASHORE26,
	& RASHORE27,
	& RASHORE28,
	& RASHORE29,
	& RASHORE30,
	& RASHORE31,
	& RASHORE32,
	& RASHORE33,
	& RASHORE34,
	& RASHORE35,
	& RASHORE36,
	& RASHORE37,
	& RASHORE38,
	& RASHORE39,
	& RASHORE40,
	& RASHORE41,
	& RASHORE42,
	& RASHORE43,
	& RASHORE44,
	& RASHORE45,
	& RASHORE46,
	& RASHORE47,
	& RASHORE48,
	& RASHORE49,
	& RASHORE50,
	& RASHORE51,
	& RASHORE52,
	& RASHORE53,
	& RASHORE54,
	& RASHORE55,
	& RASHORE56,
	& RASHORECLIFF01,
	& RASHORECLIFF02,
	& RASHORECLIFF03,
	& RASHORECLIFF04,
	& RASHORECLIFF05,
	& RASHORECLIFF06,
	& RASHORECLIFF07,
	& RASHORECLIFF08,
	& RASHORECLIFF09,
	& RASHORECLIFF10,
	& RASHORECLIFF11,
	& RASHORECLIFF12,
	& RASHORECLIFF13,
	& RASHORECLIFF14,
	& RASHORECLIFF15,
	& RASHORECLIFF16,
	& RASHORECLIFF17,
	& RASHORECLIFF18,
	& RASHORECLIFF19,
	& RASHORECLIFF20,
	& RASHORECLIFF21,
	& RASHORECLIFF22,
	& RASHORECLIFF23,
	& RASHORECLIFF24,
	& RASHORECLIFF25,
	& RASHORECLIFF26,
	& RASHORECLIFF27,
	& RASHORECLIFF28,
	& RASHORECLIFF29,
	& RASHORECLIFF30,
	& RASHORECLIFF31,
	& RASHORECLIFF32,
	& RASHORECLIFF33,
	& RASHORECLIFF34,
	& RASHORECLIFF35,
	& RASHORECLIFF36,
	& RASHORECLIFF37,
	& RASHORECLIFF38,
	& RABOULDER1,
	& RABOULDER2,
	& RABOULDER3,
	nullptr,
	nullptr,
	nullptr,
	& RAPATCH01,
	& RAPATCH02,
	& RAPATCH03,
	& RAPATCH04,
	& RAPATCH07,
	& RAPATCH08,
	& RAPATCH13,
	& RAPATCH14,
	nullptr,
	& RARIVER01,
	& RARIVER02,
	& RARIVER03,
	& RARIVER04,
	& RARIVER05,
	& RARIVER06,
	& RARIVER07,
	& RARIVER08,
	& RARIVER09,
	& RARIVER10,
	& RARIVER11,
	& RARIVER12,
	& RARIVER13,
	& RAFALLS1,
	& RAFALLS1A,
	& RAFALLS2,
	& RAFALLS2A,
	& RAFORD1,
	& RAFORD2,
	& RABRIDGE1,
	& RABRIDGE1D,
	& RABRIDGE2,
	& RABRIDGE2D,
	& RASLOPE01,
	& RASLOPE02,
	& RASLOPE03,
	& RASLOPE04,
	& RASLOPE05,
	& RASLOPE06,
	& RASLOPE07,
	& RASLOPE08,
	& RASLOPE09,
	& RASLOPE10,
	& RASLOPE11,
	& RASLOPE12,
	& RASLOPE13,
	& RASLOPE14,
	& RASLOPE15,
	& RASLOPE16,
	& RASLOPE17,
	& RASLOPE18,
	& RASLOPE19,
	& RASLOPE20,
	& RASLOPE21,
	& RASLOPE22,
	& RASLOPE23,
	& RASLOPE24,
	& RASLOPE25,
	& RASLOPE26,
	& RASLOPE27,
	& RASLOPE28,
	& RASLOPE29,
	& RASLOPE30,
	& RASLOPE31,
	& RASLOPE32,
	& RASLOPE33,
	& RASLOPE34,
	& RASLOPE35,
	& RASLOPE36,
	& RASLOPE37,
	& RASLOPE38,
	& RAROAD01,
	& RAROAD02,
	& RAROAD03,
	& RAROAD04,
	& RAROAD05,
	& RAROAD06,
	& RAROAD07,
	& RAROAD08,
	& RAROAD09,
	& RAROAD10,
	& RAROAD11,
	& RAROAD12,
	& RAROAD13,
	& RAROAD14,
	& RAROAD15,
	& RAROAD16,
	& RAROAD17,
	& RAROAD18,
	& RAROAD19,
	& RAROAD20,
	& RAROAD21,
	& RAROAD22,
	& RAROAD23,
	& RAROAD24,
	& RAROAD25,
	& RAROAD26,
	& RAROAD27,
	& RAROAD28,
	& RAROAD29,
	& RAROAD30,
	& RAROAD31,
	& RAROAD32,
	& RAROAD33,
	& RAROAD34,
	& RAROAD35,
	& RAROAD36,
	& RAROAD37,
	& RAROAD38,
	& RAROAD39,
	& RAROAD40,
	& RAROAD41,
	& RAROAD42,
	& RAROAD43,
	& RAROUGH01,
	& RAROUGH02,
	& RAROUGH03,
	& RAROUGH04,
	& RAROUGH05,
	& RAROUGH06,
	& RAROUGH07,
	& RAROUGH08,
	& RAROUGH09,
	& RAROUGH10,
	& RAROUGH11,
	& RAROAD44,
	& RAROAD45,
	& RARIVER14,
	& RARIVER15,
	& RARIVERCLIFF01,
	& RARIVERCLIFF02,
	& RARIVERCLIFF03,
	& RARIVERCLIFF04,
	& RABRIDGE1A,
	& RABRIDGE1B,
	& RABRIDGE1C,
	& RABRIDGE2A,
	& RABRIDGE2B,
	& RABRIDGE2C,
	& RABRIDGE3A,
	& RABRIDGE3B,
	& RABRIDGE3C,
	& RABRIDGE3D,
	& RABRIDGE3E,
	& RABRIDGE3F,
	& RAF01,
	& RAF02,
	& RAF03,
	& RAF04,
	& RAF05,
	& RAF06,
	& RAARRO0001,
	& RAARRO0002,
	& RAARRO0003,
	& RAARRO0004,
	& RAARRO0005,
	& RAARRO0006,
	& RAARRO0007,
	& RAARRO0008,
	& RAARRO0009,
	& RAARRO0010,
	& RAARRO0011,
	& RAARRO0012,
	& RAARRO0013,
	& RAARRO0014,
	& RAARRO0015,
	& RAFLOR0001,
	& RAFLOR0002,
	& RAFLOR0003,
	& RAFLOR0004,
	& RAFLOR0005,
	& RAFLOR0006,
	& RAFLOR0007,
	& RAGFLR0001,
	& RAGFLR0002,
	& RAGFLR0003,
	& RAGFLR0004,
	& RAGFLR0005,
	& RAGSTR0001,
	& RAGSTR0002,
	& RAGSTR0003,
	& RAGSTR0004,
	& RAGSTR0005,
	& RAGSTR0006,
	& RAGSTR0007,
	& RAGSTR0008,
	& RAGSTR0009,
	& RAGSTR0010,
	& RAGSTR0011,
	& RALWAL0001,
	& RALWAL0002,
	& RALWAL0003,
	& RALWAL0004,
	& RALWAL0005,
	& RALWAL0006,
	& RALWAL0007,
	& RALWAL0008,
	& RALWAL0009,
	& RALWAL0010,
	& RALWAL0011,
	& RALWAL0012,
	& RALWAL0013,
	& RALWAL0014,
	& RALWAL0015,
	& RALWAL0016,
	& RALWAL0017,
	& RALWAL0018,
	& RALWAL0019,
	& RALWAL0020,
	& RALWAL0021,
	& RALWAL0022,
	& RALWAL0023,
	& RALWAL0024,
	& RALWAL0025,
	& RALWAL0026,
	& RALWAL0027,
	& RASTRP0001,
	& RASTRP0002,
	& RASTRP0003,
	& RASTRP0004,
	& RASTRP0005,
	& RASTRP0006,
	& RASTRP0007,
	& RASTRP0008,
	& RASTRP0009,
	& RASTRP0010,
	& RASTRP0011,
	& RAWALL0001,
	& RAWALL0002,
	& RAWALL0003,
	& RAWALL0004,
	& RAWALL0005,
	& RAWALL0006,
	& RAWALL0007,
	& RAWALL0008,
	& RAWALL0009,
	& RAWALL0010,
	& RAWALL0011,
	& RAWALL0012,
	& RAWALL0013,
	& RAWALL0014,
	& RAWALL0015,
	& RAWALL0016,
	& RAWALL0017,
	& RAWALL0018,
	& RAWALL0019,
	& RAWALL0020,
	& RAWALL0021,
	& RAWALL0022,
	& RAWALL0023,
	& RAWALL0024,
	& RAWALL0025,
	& RAWALL0026,
	& RAWALL0027,
	& RAWALL0028,
	& RAWALL0029,
	& RAWALL0030,
	& RAWALL0031,
	& RAWALL0032,
	& RAWALL0033,
	& RAWALL0034,
	& RAWALL0035,
	& RAWALL0036,
	& RAWALL0037,
	& RAWALL0038,
	& RAWALL0039,
	& RAWALL0040,
	& RAWALL0041,
	& RAWALL0042,
	& RAWALL0043,
	& RAWALL0044,
	& RAWALL0045,
	& RAWALL0046,
	& RAWALL0047,
	& RAWALL0048,
	& RAWALL0049,
	& RABRIDGE1H,
	& RABRIDGE2H,
	& RABRIDGE1AX,
	& RABRIDGE2AX,
	& RABRIDGE1X,
	& RABRIDGE2X,
	& RAXTRA0001,
	& RAXTRA0002,
	& RAXTRA0003,
	& RAXTRA0004,
	& RAXTRA0005,
	& RAXTRA0006,
	& RAXTRA0007,
	& RAXTRA0008,
	& RAXTRA0009,
	& RAXTRA0010,
	& RAXTRA0011,
	& RAXTRA0012,
	& RAXTRA0013,
	& RAXTRA0014,
	& RAXTRA0015,
	& RAXTRA0016,
	& RAHILL01,
};

void TemplateType::Init()
{
	Gdiplus::Size size(32, 32);
	int num = max(IconWidth, IconHeight);
	Thumbnail = new Gdiplus::Bitmap(num * size.Width, num * size.Height);
	IconMask = new bool[IconWidth * IconHeight];
	memset(IconMask, 0, sizeof(*IconMask));
	Gdiplus::Graphics *g = Gdiplus::Graphics::FromImage(Thumbnail);
	g->Clear(Gdiplus::Color::Transparent);
	int num2 = 0;
	for (int i = 0; i < IconHeight; i++)
	{
		for (int j = 0; j < IconWidth; j++)
		{
			Tile *tile;
			if (TheTilesetManager->GetTileData(Name.c_str(), num2, tile))
			{
				g->DrawImage(tile->Image, j * size.Width, i * size.Height, size.Width, size.Height);
				IconMask[j + i * IconWidth] = true;
			}
			num2++;
		}
	}
	delete g;
}
