#pragma once
enum TheaterTypeTD {
	THEATER_NONETD = -1,
	THEATER_DESERTTD,
	THEATER_JUNGLETD,
	THEATER_TEMPERATETD,
	THEATER_WINTERTD,
	THEATER_COUNTTD,
	THEATER_FIRSTTD = 0
};
#define	THEATERF_DESERTTD			(1<<THEATER_DESERTTD)
#define	THEATERF_JUNGLETD			(1<<THEATER_JUNGLETD)
#define	THEATERF_TEMPERATETD		(1<<THEATER_TEMPERATETD)
#define	THEATERF_WINTERTD			(1<<THEATER_WINTERTD)
enum TheaterTypeRA {
	THEATER_NONERA = -1,
	THEATER_TEMPERATERA,
	THEATER_SNOWRA,
	THEATER_INTERIORRA,
	THEATER_COUNTRA,
	THEATER_FIRSTRA = 0
};
#define	THEATERF_TEMPERATERA		(1<<THEATER_TEMPERATERA)
#define	THEATERF_SNOWRA				(1<<THEATER_SNOWRA)
#define	THEATERF_INTERIORRA			(1<<THEATER_INTERIORRA)
