#pragma once
#include <string>
typedef enum VesselTypeRA : char {
	VESSELRA_NONE = -1,
	VESSELRA_SS,
	VESSELRA_DD,
	VESSELRA_CA,
	VESSELRA_TRANSPORT,
	VESSELRA_PT,
	VESSELRA_MISSILESUB,
	VESSELRA_CARRIER,
	VESSELRA_COUNT,
	VESSELRA_FIRST = 0
} VesselTypeRA;
